### ISSUE TITLE
New update causes game crash

### ISSUE THREAD

**Issue by Darthscion55** [WMF-Industries/NeonNights2#1]
Ohno, the game has crashed. Report this at: https://discord.gg/yp9ZW7j

Copy paste the report below when reporting:
```java
Version: release steam build 146
(Foo's Client Version: 5705419, Dec. 19, 2023)
Source: mindustry-antigrief/mindustry-client-v7-builds
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 8172mb
Cores: 8
Mods: auto-drill:1, extra-logging:2.2.0, fooinstaller:1.2.4, mi2-utilities-java:1.4.3, neonnights-2:2.1, newconsole:1.9, schem-browser:1.1, triangles:v2.7

rhino.EvaluatorException: Java class "mindustry.content.UnitTypes$45$3$1" has no public instance field or method named "backColor". (NeonBeetles#10)
	at rhino.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:68)
	at rhino.Context.reportRuntimeError(Context.java:756)
	at rhino.Context.reportRuntimeError(Context.java:802)
	at rhino.Context.reportRuntimeError2(Context.java:776)
	at rhino.JavaMembers.reportMemberNotFound(JavaMembers.java:755)
	at rhino.JavaMembers.put(JavaMembers.java:96)
	at rhino.NativeJavaObject.put(NativeJavaObject.java:93)
	at rhino.ScriptableObject.putProperty(ScriptableObject.java:2316)
	at rhino.ScriptRuntime.setObjectProp(ScriptRuntime.java:1533)
	at rhino.ScriptRuntime.setObjectProp(ScriptRuntime.java:1528)
	at rhino.gen.NeonBeetles_8._c_anonymous_3(NeonBeetles:10)
	at rhino.gen.NeonBeetles_8.call(NeonBeetles)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy2/jdk.proxy2.$Proxy7.accept(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at rhino.MemberBox.invoke(MemberBox.java:104)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.NeonBeetles_8._c_anonymous_1(NeonBeetles:8)
	at rhino.gen.NeonBeetles_8.call(NeonBeetles)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.NeonBeetles_8.call(NeonBeetles)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy1/jdk.proxy1.$Proxy1.get(Unknown Source)
	at arc.Events.fire(Events.java:90)
	at arc.Events.fire(Events.java:76)
	at mindustry.ClientLauncher.update(ClientLauncher.java:250)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:205)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:193)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:57)
```

Crash report. After updating all mods, this is causing a crash with this error 2 times in a row.

**Comment by WMF-Industries** [comment]
already on it, sorry for the issue

**Comment by Darthscion55** [comment]
> already on it, sorry for the issue

Sounds good. Thanks!

**Comment by WMF-Industries** [comment]
fixed :)
